name: Fastbreaker
main: me.data54.fastbreaker.Fastbreaker
version: 1.1
description: >
             Makes breaking things faster
commands:
  fastbreaker:
    description: Toggles Fastbreaker on/off
    usage: fastbreaker
  fb:
    description: Toggles Fastbreaker on/off
    usage: fb
  bb:
    description: Toggles Bedrock Breaker on/off
    usage: bb
    